export const complexWordDictionary: Record<string, string[]> = {
  "utilize": ["use"],
  "utilizes": ["uses"],
  "utilized": ["used"],
  "utilizing": ["using"],
  "functionality": ["features", "functions"],
  "implementation": ["setup", "use", "addition"],
  "commence": ["start", "begin"],
  "commences": ["starts", "begins"],
  "commenced": ["started", "began"],
  "commencing": ["starting", "beginning"],
  "obtain": ["get"],
  "obtains": ["gets"],
  "obtained": ["got"],
  "obtaining": ["getting"],
  "additional": ["more", "extra"],
  "optimal": ["best", "ideal"],
  "optimally": ["best", "ideally"],
  "terminate": ["end", "stop"],
  "terminates": ["ends", "stops"],
  "terminated": ["ended", "stopped"],
  "terminating": ["ending", "stopping"],
  "assist": ["help"],
  "assists": ["helps"],
  "assisted": ["helped"],
  "assisting": ["helping"],
  "facilitate": ["help", "ease", "enable"],
  "facilitates": ["helps", "eases", "enables"],
  "facilitated": ["helped", "eased", "enabled"],
  "facilitating": ["helping", "easing", "enabling"],
  "endeavor": ["try", "attempt"],
  "endeavors": ["tries", "attempts"],
  "endeavored": ["tried", "attempted"],
  "endeavoring": ["trying", "attempting"],
  "sufficient": ["enough"],
  "sufficiently": ["enough"],
  "insufficient": ["not enough"],
  "purchase": ["buy"],
  "purchases": ["buys"],
  "purchased": ["bought"],
  "purchasing": ["buying"],
  "modification": ["change", "edit"],
  "modifications": ["changes", "edits"],
  "modified": ["changed", "edited"],
  "modifying": ["changing", "editing"],
  "demonstrate": ["show", "prove"],
  "demonstrates": ["shows", "proves"],
  "demonstrated": ["showed", "proved"],
  "demonstrating": ["showing", "proving"],
  "initiate": ["start", "begin"],
  "initiates": ["starts", "begins"],
  "initiated": ["started", "began"],
  "initiating": ["starting", "beginning"],
  "interface": ["screen", "display", "view"],
  "interfaces": ["screens", "displays", "views"],
  "requirement": ["need"],
  "requirements": ["needs"],
  "necessitate": ["need", "require"],
  "necessitates": ["needs", "requires"],
  "necessitated": ["needed", "required"],
  "necessitating": ["needing", "requiring"],
  "completion": ["end", "finish"],
  "completions": ["ends", "finishes"],
  "completed": ["ended", "finished", "done"],
  "completing": ["ending", "finishing"],
  "subsequently": ["then", "next", "after"],
  "furthermore": ["also", "plus", "next"],
  "moreover": ["also", "plus", "too"]
};